name: Update install.sh
on:
  release:
    types: [published, unpublished, deleted]
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run script
        run: |
          set -e -x
          git fetch origin master --tags
          git checkout -B master origin/master
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com>"
          git config user.name "github-actions[bot]"
          for channel in nightly beta release; do
            TAG_NAME=$(git tag -l --sort -version:refname | grep -F "${channel}" | head -n1 || true)
            if [ -n "${TAG_NAME}" ]; then
              git fetch origin ${channel}
              git checkout -B ${channel} origin/${channel}
              curl -fsSL "https://github.com/AdguardTeam/AdGuardCLI/releases/download/${TAG_NAME}/install.sh" -o "install.sh"
              git add "install.sh"
              if ! git diff-index --cached --quiet HEAD; then
                git commit -m "Update install.sh"
                git push origin HEAD
              fi
            fi
          done
